### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Sumitbelkar** [Cyber-Dioxide/Wifi-Brute#7]
Getting error such as 
Traceback (most recent call last):
Please help me

![Screenshot_2023-02-04-00-43-33-09_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/105590152/216687792-c10f5005-52dc-466e-abf0-c640c381e65c.jpg)

**Comment by Sumitbelkar** [comment]
How can I resolve this issue

**Comment by Cyber-Dioxide** [comment]
This issue is on android, install kali nethunter and root your phone, it may work perfect
